{{- if .Values.dockerRegSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: docker-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerRegSecret }}
{{- end }}